version: '3'
services:
    email:
        build: .
        container_name: "email"
        image: email:latest
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command:  --storageEngine=wiredTiger