version: '3'
services:
    email:
        build: .
        container_name: "email"
        image: email:latest
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
#        environment:
#          - MONGO_INITDB_DATABASE=email_bot
#          - MONGO_DATA_DIR=/data/db
        volumes:
#          - ./data/db:/data/db
          - ./lol:/docker-entrypoint-initdb.d
        ports:
            - 27017:27017
        command:  --storageEngine=wiredTiger