language: java
sudo: true
jdk: 
      - oraclejdk8

jobs:
  include:
    - stage: fullBuild
      script:
        - mvn clean install
      after_success:
        - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=integration-test/target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN  -DapiToken=$CODACY_API_TOKEN
    - stage: emailBuild
      before_install:
        - chmod +x email/gradlew
      script:
        - cd email && ./gradlew assembJar