language: java
sudo: true
jdk: 
      - oraclejdk8

before_install:
 - chmod +x email/gradlew

script:
  - mvn clean install
  - cd email
  - ./gradlew clean
  - ./gradlew assembJar
  - cd build/libs
  - ls -la

after_success:
  - cd ./integration-test
  - pwd
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN  -DapiToken=$CODACY_API_TOKEN
